name: Java CI with Maven and Release

on:
  push:
    branches: [ "none" ]

jobs:
  build_and_release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run:  mvn clean javafx:jlink

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageSorterPro-${{ matrix.os }}
          path: target/ImageSorterPro-*.jar

  release:
    needs: build_and_release
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
